### ISSUE TITLE
Modification 

### ISSUE THREAD

**Issue by MrJuju0319** [megastorage/Nut_Free#1]
Bonjour, 
est-il possible d'avoir une valeur libre pour le temps restant, car il est actuellement en secondes, alors je les convertie en minutes car plus facile a lire

merci

**Comment by megastorage** [comment]
Bonsoir,

Le plugin fait que remonter les infos du serveur nut qui sont en secondes.

Je vais voir pour ajouter une option dans la page de config pour afficher
en minutes ou en secondes. Chaque utilisateur veux afficher de manière
différente. Il est donc difficile de satisfaire tout le monde.

Je penses que ça sera un bon compromis pour tout le monde

Je regarderais quand j'aurais le temps. Pas de délais pour le moment.

Stef.

Le dim. 2 févr. 2020 à 19:21, MrJuju0319 <notifications@github.com> a
écrit :

**Comment by MrJuju0319** [comment]
D'accord pas de problème, après moi j'ai divisé la valeur reçu par 60 pour la mettre en minutes, 
Soit un case a cocher ou justes ne pas mettre de valeur fixe; je pense 

Merci

**Comment by megastorage** [comment]
Je ne comprend pas " ne pas mettre de valeur fixe"
Je vais afficher la valeur en double en seconde et minutes ca me fera moins
de modif et une meilleur gestion pour l'historique.

Stef.

Le dim. 2 févr. 2020 à 21:06, MrJuju0319 <notifications@github.com> a
écrit :

**Comment by megastorage** [comment]
Pour info, la modif est prete ici.

Tu peux dowloadé depuis ici et mettre dans le dossier plugin pour voir.
J'ai juste dupliqué les commandes et mis sans virgules pour l'historique.

Stef.

**Comment by megastorage** [comment]
Je viens de pousser vers la beta; si tu veux tester.

Stef.

**Comment by MrJuju0319** [comment]
Désolé j'ai pas vue mes mail, je teste sa ce soir

Le mar. 4 févr. 2020 à 19:39, megastorage <notifications@github.com> a
écrit :

**Comment by MrJuju0319** [comment]
C'est NIQUEL merci pour ta réactivité
